export const manufacturers = [
  { title: "Acura", value: "Acura" },
  { title: "Alfa Romeo", value: "Alfa Romeo" },
  { title: "Aston Martin", value: "Aston Martin" },
  { title: "Audi", value: "Audi" },
  { title: "Bentley", value: "Bentley" },
  { title: "BMW", value: "BMW" },
  { title: "Buick", value: "Buick" },
  { title: "Cadillac", value: "Cadillac" },
  { title: "Chevrolet", value: "Chevrolet" },
  { title: "Chrysler", value: "Chrysler" },
  { title: "Citroen", value: "Citroen" },
  { title: "Dodge", value: "Dodge" },
  { title: "Ferrari", value: "Ferrari" },
  { title: "Fiat", value: "Fiat" },
  { title: "Ford", value: "Ford" },
  { title: "GMC", value: "GMC" },
  { title: "Honda", value: "Honda" },
  { title: "Hyundai", value: "Hyundai" },
  { title: "Infiniti", value: "Infiniti" },
  { title: "Jaguar", value: "Jaguar" },
  { title: "Jeep", value: "Jeep" },
  { title: "Kia", value: "Kia" },
  { title: "Lamborghini", value: "Lamborghini" },
  { title: "Land Rover", value: "Land Rover" },
  { title: "Lexus", value: "Lexus" },
  { title: "Lincoln", value: "Lincoln" },
  { title: "Maserati", value: "Maserati" },
  { title: "Mazda", value: "Mazda" },
  { title: "McLaren", value: "McLaren" },
  { title: "Mercedes-Benz", value: "Mercedes-Benz" },
  { title: "MINI", value: "MINI" },
  { title: "Mitsubishi", value: "Mitsubishi" },
  { title: "Nissan", value: "Nissan" },
  { title: "Porsche", value: "Porsche" },
  { title: "Ram", value: "Ram" },
  { title: "Rolls-Royce", value: "Rolls-Royce" },
  { title: "Subaru", value: "Subaru" },
  { title: "Tesla", value: "Tesla" },
  { title: "Toyota", value: "Toyota" },
  { title: "Volkswagen", value: "Volkswagen" },
  { title: "Volvo", value: "Volvo" },
];

export const yearsOfProduction = [
  { title: "1985", value: "1985" },
  { title: "1993", value: "1993" },
  { title: "1994", value: "1994" },
  { title: "1995", value: "1995" },
  { title: "1996", value: "1996" },
  { title: "1997", value: "1997" },
  { title: "1998", value: "1998" },
  { title: "1999", value: "1999" },
  { title: "2000", value: "2000" },
  { title: "2001", value: "2001" },
  { title: "2002", value: "2002" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
  { title: "2025", value: "2025" },
];

export const fuels = [
  {
    title: "Gas",
    value: "gas",
  },
  {
    title: "Diesel",
    value: "diesel",
  },
  {
    title: "Electric",
    value: "electricity",
  },
];

export const cars = {
  acura: "/cars/acura.png",
  alfaromeo: "/cars/alfa-romeo.png",
  astonmartin: "/cars/aston-martin.png",
  audi: "/cars/audi.png",
  bentley: "/cars/bentley.png",
  bmw: "/cars/bmw.png",
  buick: "/cars/buickk.png",
  cadillac: "/cars/cadillac.png",
  chevrolet: "/cars/chevrolett.png",
  chrysler: "/cars/chrysler.png",
  citroen: "/cars/citroen.png",
  dodge: "/cars/dodge.png",
  ferrari: "/cars/ferrari.png",
  fiat: "/cars/fiat.png",
  ford: "/cars/ford.png",
  gmc: "/cars/gmc.png",
  honda: "/cars/honda.png",
  hyundai: "/cars/hyundai.png",
  infiniti: "/cars/infiniti.png",
  jaguar: "/cars/jaguar.png",
  jeep: "/cars/jeep.png",
  kia: "/cars/kia.png",
  lamborghini: "/cars/lamborghini.png",
  landrover: "/cars/land-rover.png",
  lexus: "/cars/lexus.png",
  lincoln: "/cars/lincoln.png",
  maserati: "/cars/maserati.png",
  mazda: "/cars/mazda.png",
  mclaren: "/cars/mclaren.png",
  mercedesbenz: "/cars/mercedes-benz.png",
  mini: "/cars/mini.png",
  mitsubishi: "/cars/mitsubishi.png",
  nissan: "/cars/nissan.png",
  porsche: "/cars/porsche.png",
  ram: "/cars/ram.png",
  rollsroyce: "/cars/rolls-royce.png",
  subaru: "/cars/subaru.png",
  tesla: "/cars/tesla.png",
  toyota: "/cars/toyota.png",
  volkswagen: "/cars/volks-wagen.png",
  volvo: "/cars/volvo.png",
};

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
