export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
  { title: "2025", value: "2025" },
];

export const fuels = [
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const cars = {
  acura: "/cars/acura.png",
  alfaromeo: "/cars/alfa-romeo.png",
  astonmartin: "/cars/aston-martin.png",
  audi: "/cars/audi.png",
  bentley: "/cars/bentley.png",
  bmw: "/cars/bmw.png",
  buick: "/cars/buickk.png",
  cadillac: "/cars/cadillac.png",
  chevrolet: "/cars/chevrolett.png",
  chrysler: "/cars/chrysler.png",
  citroen: "/cars/citroen.png",
  dodge: "/cars/dodge.png",
  ferrari: "/cars/ferrari.png",
  fiat: "/cars/fiat.png",
  ford: "/cars/ford.png",
  gmc: "/cars/gmc.png",
  honda: "/cars/honda.png",
  hyundai: "/cars/hyundai.png",
  infiniti: "/cars/infiniti.png",
  jaguar: "/cars/jaguar.png",
  jeep: "/cars/jeep.png",
  kia: "/cars/kia.png",
  lamborghini: "/cars/lamborghini.png",
  landrover: "/cars/land-rover.png",
  lexus: "/cars/lexus.png",
  lincoln: "/cars/lincoln.png",
  maserati: "/cars/maserati.png",
  mazda: "/cars/mazda.png",
  mclaren: "/cars/mclaren.png",
  mercedesbenz: "/cars/mercedes-benz.png",
  mini: "/cars/mini.png",
  mitsubishi: "/cars/mitsubishi.png",
  nissan: "/cars/nissan.png",
  porsche: "/cars/porsche.png",
  ram: "/cars/ram.png",
  rollsroyce: "/cars/rolls-royce.png",
  subaru: "/cars/subaru.png",
  tesla: "/cars/tesla.png",
  toyota: "/cars/toyota.png",
  volkswagen: "/cars/volks-wagen.png",
  volvo: "/cars/volvo.png",
};

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
