export const manufacturers = [
  { title: "Acura", value: "Acura", models: ["nsx", "integra"] },
  { title: "Alfa Romeo", value: "Alfa Romeo", models: ["spider, 164"] },
  {
    title: "Aston Martin",
    value: "Aston Martin",
    models: ["virage/volante", "db7 coupe", "lagonda"],
  },
  {
    title: "Audi",
    value: "Audi",
    models: ["4000s quattro", "100", "cabriolet", "tt roadster"],
  },
  {
    title: "Bentley",
    value: "Bentley",
    models: ["continental gt convertible", "azure", "arnage"],
  },
  {
    title: "BMW",
    value: "BMW",
    models: ["5 series", "740i", "318i convertible", "z3 roadster"],
  },
  {
    title: "Buick",
    value: "Buick",
    models: ["riviera convertible", "century", "skylark"],
  },
  { title: "Cadillac", value: "Cadillac", models: ["cimarron", "eldorado"] },
  {
    title: "Chevrolet",
    value: "Chevrolet",
    models: ["suburban c10 2wd", "lumina", "corvette"],
  },
  {
    title: "Chrysler",
    value: "Chrysler",
    models: ["laser", "new yorker", "lebaron convertible", "sebring"],
  },
  { title: "Citroen", value: "Citroen", models: ["charger", "dynasty"] },
  {
    title: "Dodge",
    value: "Dodge",
    models: ["dynasty", "viper", "avenger", "viper convertible"],
  },
  {
    title: "Ferrari",
    value: "Ferrari",
    models: [
      "ferrari 550 maranello",
      "testarossa",
      "348 tb/ts",
      "ferrari 348 tb/ts/spider",
      "ferrari f355 berlinetta/gts",
    ],
  },
  { title: "Fiat", value: "Fiat", models: ["500"] },
  {
    title: "Ford",
    value: "Ford",
    models: ["taurus", "e150 club wagon", "aspire", "escort zx2"],
  },
  {
    title: "GMC",
    value: "GMC",
    models: ["sonoma 2wd", "g15/25 rally 2wd", "sonoma 2wd"],
  },
  {
    title: "Honda",
    value: "Honda",
    models: ["civic", "civic crx", "accord wagon", "civic del sol"],
  },
  {
    title: "Hyundai",
    value: "Hyundai",
    models: ["scoupe", "excel", "sonata", "tiburon (coupe)", "accent"],
  },
  { title: "Infiniti", value: "Infiniti", models: ["j30", "q45"] },
  {
    title: "Jaguar",
    value: "Jaguar",
    models: ["xjs convertible", "xjs", "xj6", "xjs v12 convertible"],
  },
  {
    title: "Jeep",
    value: "Jeep",
    models: [
      "grand cherokee 2wd",
      "cherokee/wagoneer",
      "comanche pickup 4wd",
      "cherokee 2wd",
    ],
  },
  { title: "Kia", value: "Kia", models: ["sephia", "rio"] },
  {
    title: "Lamborghini",
    value: "Lamborghini",
    models: ["l-147 murcielago", "db132/diablo", "db132/144 - diablo"],
  },
  {
    title: "Land Rover",
    value: "Land Rover",
    models: ["defender 90", "defender 110", "discovery"],
  },
  { title: "Lexus", value: "Lexus", models: ["sc 300/sc 400", "ls 400"] },
  {
    title: "Lincoln",
    value: "Lincoln",
    models: ["mark viii", "continental", "mark viii"],
  },
  {
    title: "Maserati",
    value: "Maserati",
    models: ["biturbo", "spider cambiocorsa/spider gt", "ghibli sq4"],
  }, //image
  {
    title: "Mazda",
    value: "Mazda",
    models: ["3 4-door 4wd", "rx-7", "626", "mx-5 miata"],
  },
  { title: "McLaren", value: "McLaren", models: ["570gt", "gt", "720s coupe"] }, //image
  {
    title: "Mercedes Benz",
    value: "Mercedes-Benz",
    models: ["a220 4matic", "500sl", "300sd", "sl320"],
  },
  { title: "MINI", value: "MINI", models: ["cooper convertible"] },
  {
    title: "Mitsubishi",
    value: "Mitsubishi",
    models: [
      "eclipse cross 2wd",
      "montero 4wd",
      "expo",
      "mirage",
      "eclipse",
      "eclipse convertible",
    ],
  },
  {
    title: "Nissan",
    value: "Nissan",
    models: ["300zx", "truck cab chassis 2wd", "maxima"],
  },
  {
    title: "Porsche",
    value: "Porsche",
    models: ["911 carrera 4/2", "944", "968", "boxster", "911 gt2"],
  },
  { title: "Ram", value: "Ram", models: ["1500 2wd", "c/v cargo van"] },
  {
    title: "Rolls Royce",
    value: "Rolls-Royce",
    models: [
      "phantom",
      "continental",
      "brooklands/brklnds l",
      "corniche/continental",
      "azure",
    ],
  },
  {
    title: "Subaru",
    value: "Subaru",
    models: [
      "impreza",
      "brat 4wd",
      "ascent",
      "legacy awd turbo",
      "impreza",
      "impreza awd",
    ],
  },
  {
    title: "Tesla",
    value: "Tesla",
    models: [
      "model 3 long range",
      "model 3 mid range",
      "model 3 long range awd",
    ],
  },
  {
    title: "Toyota",
    value: "Toyota",
    models: ["van 2wd", "corolla", "mr2", "celica convertible", "gr 86"],
  },
  {
    title: "Volkswagen",
    value: "Volkswagen",
    models: [
      "golf-r",
      "vanagon 2wd",
      "cabrio",
      "golf iii / gti",
      "corrado slc",
    ],
  },
  {
    title: "Volvo",
    value: "Volvo",
    models: [
      "c70 convertible",
      "240 dl/gl/turbo",
      "240",
      "850",
      "960",
      "960/s90",
    ],
  },
];

export const yearsOfProduction = [
  { title: "1985", value: "1985" },
  { title: "1993", value: "1993" },
  { title: "1994", value: "1994" },
  { title: "1995", value: "1995" },
  { title: "1996", value: "1996" },
  { title: "1997", value: "1997" },
  { title: "1998", value: "1998" },
  { title: "1999", value: "1999" },
  { title: "2000", value: "2000" },
  { title: "2001", value: "2001" },
  { title: "2002", value: "2002" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
  { title: "2024", value: "2024" },
  { title: "2025", value: "2025" },
];

export const fuels = [
  {
    title: "Gas",
    value: "gas",
  },
  {
    title: "Diesel",
    value: "diesel",
  },
  {
    title: "Electric",
    value: "electricity",
  },
];

export const cars = {
  acura: "/cars/acura.png",
  alfaromeo: "/cars/alfa-romeo.png",
  astonmartin: "/cars/aston-martin.png",
  audi: "/cars/audi.png",
  bentley: "/cars/bentley.png",
  bmw: "/cars/bmw.png",
  buick: "/cars/buickk.png",
  cadillac: "/cars/cadillac.png",
  chevrolet: "/cars/chevrolett.png",
  chrysler: "/cars/chrysler.png",
  citroen: "/cars/citroen.png",
  dodge: "/cars/dodge.png",
  ferrari: "/cars/ferrari.png",
  fiat: "/cars/fiat.png",
  ford: "/cars/ford.png",
  gmc: "/cars/gmc.png",
  honda: "/cars/honda.png",
  hyundai: "/cars/hyundai.png",
  infiniti: "/cars/infiniti.png",
  jaguar: "/cars/jaguar.png",
  jeep: "/cars/jeep.png",
  kia: "/cars/kia.png",
  lamborghini: "/cars/lamborghini.png",
  landrover: "/cars/land-rover.png",
  lexus: "/cars/lexus.png",
  lincoln: "/cars/lincoln.png",
  maserati: "/cars/maserati.png",
  mazda: "/cars/mazda.png",
  mclaren: "/cars/mclaren.png",
  mercedesbenz: "/cars/mercedes.png",
  mini: "/cars/mini.png",
  mitsubishi: "/cars/mitsubishi.png",
  nissan: "/cars/nissan.png",
  porsche: "/cars/porsche.png",
  ram: "/cars/ram.png",
  rollsroyce: "/cars/rolls-royce.png",
  subaru: "/cars/subaru.png",
  tesla: "/cars/tesla.png",
  toyota: "/cars/toyota.png",
  volkswagen: "/cars/volks-wagen.png",
  volvo: "/cars/volvo.png",
};

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
